### ISSUE TITLE
Empty Watch box

### ISSUE THREAD

**Issue by shivaprashanth18** [Sayches/feedback#13]
**To Reproduce**
1. Go to 'feed'
2. check  'watch' right hand menus

**Expected behavior**
show me list of suggesting users. 

**Screenshots**
<img width="292" alt="watch" src="https://user-images.githubusercontent.com/64399473/121760303-a36edb80-cb47-11eb-948d-616e4c2fd764.PNG">

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
