### ISSUE TITLE
No Validation in Newsroom and help

### ISSUE THREAD

**Issue by shivaprashanth18** [Sayches/feedback#14]
**To Reproduce**
1. Go to 'Newsroom'
2. Click on 'search bar'
3. Write very long text

**Expected behavior**
it should be limited text length

**Screenshots**
<img width="563" alt="news-room" src="https://user-images.githubusercontent.com/64399473/121760660-9357fb80-cb49-11eb-8b85-8c3c2b1202da.PNG">
<img width="791" alt="help" src="https://user-images.githubusercontent.com/64399473/121760696-b5ea1480-cb49-11eb-9316-e952c88184c7.PNG">

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
