### ISSUE TITLE
Still can access login page while i am already logged in 

### ISSUE THREAD

**Issue by shivaprashanth18** [Sayches/feedback#15]
**To Reproduce**
1. Go to 'feed'
2. change the Url  to "https://sayches.com/login"

**Expected behavior**
Login page must be accessed only if I am not logged .

**Screenshots**
<img width="939" alt="login-error" src="https://user-images.githubusercontent.com/64399473/121761622-88ec3080-cb4e-11eb-81f6-cddad19d4c85.PNG">

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
