### ISSUE TITLE
Pong is not responsing 

### ISSUE THREAD

**Issue by shivaprashanth18** [Sayches/feedback#16]
**To Reproduce**
1. Go to 'Feed'
2. Let another user ping you 
3. Respond with Pong

**Expected behavior**
Pong should disable after clicking on it.

**Screenshots**
<img width="346" alt="Notification" src="https://user-images.githubusercontent.com/64399473/121761842-eaf96580-cb4f-11eb-8429-ecec2fa8360c.PNG">

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
