### ISSUE TITLE
Posting multiple times 

### ISSUE THREAD

**Issue by shahidkarimi** [Sayches/feedback#17]
If the pop button is pressed multiple times with minimum delay it posts feed multiple times.
To Reproduce:

1. Go To https://sayches.com/
2. Enter something in the feed textbox
3. Press the pop button simultaneously without delay

Expected behavior:
Should not post feed multiple times on clicking the POP button multiple times

OS: Linux (Ubuntu 20.04)

Browser: Chrome

**Comment by mdPT8UyRWfj27c3** [comment]
https://stackoverflow.com/questions/442678/preventing-double-http-post

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
