### ISSUE TITLE
No validation error for empty name (use spaces) and wrong mail id.

### ISSUE THREAD

**Issue by mbaliit** [Sayches/feedback#2]
**Describe the bug**
Validation error is not shown if enter space and invalid mail

**To Reproduce**
1. Go to 'https://sayches.com/'
2. Click on 'signup' button
3. Enter spacebar from keyboard on name field.
4. Enter invalid mailid on 'Email' field.
5. No validation error would be shown after click on '1-Click' button.

**Expected behavior**
Validation error would be shown if name has only spaces and invalid mailid.

**Screenshots**
![image](https://user-images.githubusercontent.com/85152868/120283649-086d3a80-c2d9-11eb-9239-0cb732c08747.png)

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
