### ISSUE TITLE
Server Error 500 shown after entering very long name and mailid.

### ISSUE THREAD

**Issue by mbaliit** [Sayches/feedback#3]
**Describe the bug**
When a long name say 1000 characters name and mailid is entered on signup page and click on save.
Then Sever error(500) is shown.

**To Reproduce**

1)Go to 'https://sayches.com/'
2)Click on 'signup' button
3)Enter 1000 or more characters length name on name field.
4)Enter 1000 or more characters length on 'Email' field.
5)Click on '1-Click' button.
6)Server Error (500) is shown.

**Expected behavior**
Max Length validation would be shown when exceeds the max length limits.

**Screenshots**
![image](https://user-images.githubusercontent.com/85152868/120286956-66e7e800-c2dc-11eb-9a57-19694bb75078.png)

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
