### ISSUE TITLE
No validation error is shown entering very long search text.

### ISSUE THREAD

**Issue by mbaliit** [Sayches/feedback#6]
**Describe the bug**
When a long search text say 1000 characters or may be more is entered on home page and click  enters.

**To Reproduce**
1)Go to 'https://sayches.com/'
2)Enter 1000 or more characters length on search field.
3)Click enter from keyboard button.
5)Check URL of the application that becomes messy with huge search text.

**Expected behavior**
there should be some validation that search text cannot be more than this number of characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/85152868/120460777-0bd6f380-c3b7-11eb-8a66-1e08dc851843.png)

![image](https://user-images.githubusercontent.com/85152868/120460864-1f825a00-c3b7-11eb-8786-18139cd51822.png)

**Comment by mdPT8UyRWfj27c3** [comment]
Min 2 characters Max 100 characters

**Comment by mdPT8UyRWfj27c3** [comment]
<img width="450" alt="Screenshot 2021-06-05 at 12 53 25" src="https://user-images.githubusercontent.com/61336552/120890821-07038100-c5fd-11eb-8036-215869d2bfc4.png">

**Comment by mdPT8UyRWfj27c3** [comment]
Fixed.
